### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Na-Nazhou** [Na-Nazhou/express-react-postgres#1]
- [ ] deploy to Heroku
- [ ] set up CI, Eslint
- [ ] set up database connection 
- [ ] learn frontend stack: react, react router, semantic-ui-react, axios (for API calls)
- [ ] learn backend stack: psql, express mvc, routes (API endpoints)
- [ ] decide package for user auth
